### ISSUE TITLE
Package as exe file can not run, how to solve？

### ISSUE THREAD

**Issue by xds-sdx** [3mora2/WPP_Whatsapp#14]
The code works fine in Pycharm, but as an exe file does not work, this error is displayed, how can I solve it?

 **error**：FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xds\\AppData\\Local\\Temp\\_MEI62322\\playwright_stealth\\js\\chrome.csi.js'

**Comment by 3mora2** [comment]
if used pyinstaller add path of playwright_stealth\js and WPP_Whatsapp\js_lib

`pyinstaller --add-data "YOUR_APTH_TO_\site-packages\playwright_stealth\js;playwright_stealth\js" --add-data "YOUR_APTH_TO_\site-packages\WPP_Whatsapp\js_lib;WPP_Whatsapp\js_lib"`
replace `YOUR_APTH_TO_` with your path to python libs

**Comment by xds-sdx** [comment]
> if used pyinstaller add path of playwright_stealth\js and WPP_Whatsapp\js_lib
> 
> `pyinstaller --add-data "YOUR_APTH_TO_\site-packages\playwright_stealth\js;playwright_stealth\js" --add-data "YOUR_APTH_TO_\site-packages\WPP_Whatsapp\js_lib;WPP_Whatsapp\js_lib"` replace `YOUR_APTH_TO_` with your path to python libs
I made the replacement according to what you said, but now the error is shown like this
error: No such file or directory: 'chrome.csi.js'
This is my revised version：
pyinstaller -F -w --add-data "D:\python\Lib\site-packages\playwright_stealth\js;playwright_stealth\js" --add-data "D:\python\Lib\site-packages\WPP_Whatsapp\js_lib;WPP_Whatsapp\js_lib" main.py

**Comment by 3mora2** [comment]
please add full error
and what your system

**Comment by xds-sdx** [comment]
Problem solved,thank you very much for your help!
