### ISSUE TITLE
How to make client.getMessages() work

### ISSUE THREAD

**Issue by alexferra** [3mora2/WPP_Whatsapp#17]
Hello, 

how does client.getMessages() work ?

Im able to send messages but not open a certain chat and get messages. 
how can I get the chatID for a specific user? How to get the chatid by having the userId and then getting all messages from them?

thank you in advance

**Comment by 3mora2** [comment]
userId or chatid is same -> `[number]@c.us` or user number only and will fix it

```
user_number = "2010******"
messages =  client.getMessages(user_number )
```

**Comment by alexferra** [comment]
@3mora2 
![image](https://github.com/3mora2/WPP_Whatsapp/assets/14792671/2ac99c3d-bec5-4b3a-a5f3-43f155b11b2d)
I get this error. The same number works to send message to, but I can't getMessages, I can also get unread messages successfully

the  client.getMessages(user_number ) returns this error

**Comment by 3mora2** [comment]
It's not error, it was async method but i update it, so update lib by use
`pip install git+https://github.com/3mora2/WPP_Whatsapp`

**Comment by alexferra** [comment]
@3mora2 I tried calling with await and also updating but still getting same error. Also tried other get messages methods and similar issue.

**Comment by 3mora2** [comment]
I try [get_messages](https://github.com/3mora2/WPP_Whatsapp/tree/main/examples/get_messages.py) now and it work fine
post full error

**Comment by alexferra** [comment]
if I use await I get:

  File "C:\Users\Alefe\AppData\Roaming\Python\Python311\site-packages\WPP_Whatsapp\api\layers\HostLayer.py", line 108, in <lambda>
    self.page.on('close', lambda: self.clearInterval(self.checkStartInterval))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Whatsapp' object has no attribute 'checkStartInterval'


If I use 1.5.1, I get the same issue I initially posted.

@3mora2 can you push the change to a new package ?

**Comment by 3mora2** [comment]
update now
pip install git+https://github.com/3mora2/WPP_Whatsapp

**Comment by alexferra** [comment]
![image](https://github.com/3mora2/WPP_Whatsapp/assets/14792671/082880ac-47c3-4517-8be5-dfe011a785ab)
@3mora2 can you please update the package

**Comment by 3mora2** [comment]
Ok
