### ISSUE TITLE
Send Video 

### ISSUE THREAD

**Issue by Jeck-Liu-Create** [3mora2/WPP_Whatsapp#20]
If I wish to send a video in mp4 format, how do I send it?

**Comment by Jeck-Liu-Create** [comment]
TitlesendFile Method Leading to Premature Python Function Completion

Description:

I havesendFile method within a Python class that is intended to send video messages. The send_video_message function calls sendFile, which uses asynchronous JavaScript syntax. The problem arises because the results from the JavaScript function appear to be returned after the send_video_message function has already completed execution, leading to an "An error occurred" message.

The core of the issue seems to be the asynchronous nature of the JavaScript code that is executed by a method named sync_page_evaluate within theThreadsafeBrowser class.

Here
```
def send_video_message(self, to, video_path, caption=None):
    try:
        result = self.client.sendFile(
            to=to,
            pathOrBase64=video_path,
            nameOrOptions='video.mp4',
            caption=caption
        )
        if result.get('sendMsgResult', {}).get('messageSendResult') == 'OK':
            print("Video File sent successfully:", result)
            return True
        else:
            print("Video File sent failed:", result)
            return False
    except Exception as e:
        print("An error occurred:", e)
        return False
```
And heresendFile method that

```
def sendFile(self, to, pathOrBase64, nameOrOptions, caption):
    to = self.valid_chatId(to)
    options = {"type": 'auto-detect'}
    if isinstance(nameOrOptions, str):
        options["filename"] = nameOrOptions
        options["caption"] = caption
    elif isinstance(nameOrOptions, dict):
        options = nameOrOptions

    _base64 = ''
    if pathOrBase64.startswith('data:'):
        _base64 = pathOrBase64
    else:
        if pathOrBase64 and os.path.exists(pathOrBase64):
            _base64 = self.convert_to_base64(pathOrBase64)
        if not options.get("filename"):
            options["filename"] = os.path.basename(pathOrBase64)
    if not _base64:
        raise Exception("Empty or invalid file or base64")

    return self.ThreadsafeBrowser.sync_page_evaluate("""async ({ to, base64, options }) => {
    const result = await WPP.chat.sendFileMessage(to, base64, options);
    return {
      ack: result.ack,
      id: result.id,
      sendMsgResult: await result.sendMsgResult,
    };
  }""", {"to": to, "base64": _base64, "options": options})
```
The issue I need to resolve is how to correctly wait for the asynchronous JavaScript function to complete and return the result to the Python method, so that I can accurately log whether the sending of the video message was successful or not. It seems that the sync_page_evaluate method might not be handling the asynchronous operation as expected, causing the Python code to proceed before the JavaScript promise is fulfilled. Any suggestions or advice on how to ensure the Python function waits for the complete result from the JavaScript function would be greatly appreciated.

**Comment by 3mora2** [comment]
error is like: `playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.` ?

**Comment by 3mora2** [comment]
update from git and try:
`result = self.client.sendFile(..., timeout_=60)`
timeout_ : second

**Comment by Jeck-Liu-Create** [comment]
This problem can occur when sending pictures or messages when the network is not good.

**Comment by Jeck-Liu-Create** [comment]
Is there a function that can query the dialog box and query whether the message has been sent, so it may not be more practical to wait until the result

**Comment by 3mora2** [comment]
All method should be async so we should as it with await 
To use them in sync function, we use run_thafe, run thafe need time out 
In your case send media take lone time, so custom time out or use async
