### ISSUE TITLE
Enable Newsletter

### ISSUE THREAD

**Issue by Patrickph** [3mora2/WPP_Whatsapp#21]
Hello it's me again, firstly Happy New Year, From what I saw in the hostsLayer file it filters only for @c.us and @g.us but now WPP already has the @newsletter function it would be good to add it, I would do it a fork to add this but I think it's more honest to inform you so you can do it yourself since it's your project.

**Comment by 3mora2** [comment]
you can add it, and pull request 
or tell me about @newsletter

**Comment by Patrickph** [comment]
I made the change.

**Comment by 3mora2** [comment]
ok, i will pull request

**Comment by Patrickph** [comment]
:) another feature for my favorite library, Happy New Year to you and your family
