### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by aomar2010** [3mora2/WPP_Whatsapp#3]
Hi dear , 

could you please add comment about how to run the app

**Comment by aomar2010** [comment]
> sync start
> 
> ```
> from WPP_Whatsapp import Create
> 
> # pass your session name
> self = Create(session="test")
> self.async_to_sync(self.start())
> ```
> 
> use `self.async_to_sync` to use async function as sync, i mean with out add `await`, if you need start clinet call `await self.start()` in async function or call `self.async_to_sync(self.start())`

Happy Eid Adha, it would be great help if you add in the project an example method , specially I'n not good I'm python

**Comment by aomar2010** [comment]
> Happy Eid Adha, you want send or receive messages

yes please

**Comment by 3mora2** [comment]
see [examples](https://github.com/3mora2/WPP_Whatsapp/tree/main/examples)

**Comment by 3mora2** [comment]
@aomar2010 
install new update `pip install WPP_Whatsapp -U` and try [examples](https://github.com/3mora2/WPP_Whatsapp/tree/main/examples)

**Comment by aomar2010** [comment]
> @aomar2010 install new update `pip install WPP_Whatsapp -U` and try [examples](https://github.com/3mora2/WPP_Whatsapp/tree/main/examples)

thank you Ammar , it works
