### ISSUE TITLE
was working recently, updated to the latest version and just timesouts client = creator.start()

### ISSUE THREAD

**Issue by alexferra** [3mora2/WPP_Whatsapp#38]
was working recently, updated to the latest version and just timesouts client = creator.start()

**Comment by 3mora2** [comment]
Send all logs and error

**Comment by alexferra** [comment]
the first time it works, after its linked, if I run it I get that

**Comment by 3mora2** [comment]
Error say that qrcode not load
May be 
- you use Firefox without headless mode, Firefox take long time to do action and need tab to be focus
- You can use chromium or other than Firefox 
- try start with async no time out

**Comment by alexferra** [comment]
I use chromium . it doesn't work after the first run.

**Comment by 3mora2** [comment]
What version you used

**Comment by alexferra** [comment]
thanks updating that worked
