### ISSUE TITLE
using wpp_whatsapp and pyqt

### ISSUE THREAD

**Issue by subcriminal** [3mora2/WPP_Whatsapp#47]
when integrating wpp_whatsapp with pyqt , doing send message process leaving asyncio_0 open in the background without closing it not matter what i tried to do.....

its not from pyqt for sure

**Comment by 3mora2** [comment]
you need close creator `creator.sync_close()`
in your case, pyqt has method `closeEvent` callback when close qt app
```python
    def closeEvent(self, a0):
        if hasattr(self, "creator") and self.creator:
            self.creator.sync_close()

```
