### ISSUE TITLE
asyncio\tasks.py", line 922, in run_coroutine_threadsafe     raise TypeError('A coroutine object is required')

### ISSUE THREAD

**Issue by homeplaya** [3mora2/WPP_Whatsapp#50]
Hi, I upgraded to the last version, however I am having this error :

asyncio\tasks.py", line 922, in run_coroutine_threadsafe
    raise TypeError('A coroutine object is required')

Strangely browser opens and shuts down immediately with the mentioned error.

I changed the session name and the session folders were deleted and new ones created but problem persists.

**Comment by 3mora2** [comment]
Update for now `pip install -U PlaywrightSafeThread`
 ,will fix it soon
