### ISSUE TITLE
is it possible to register whatsapp using this method?

### ISSUE THREAD

**Issue by ItzmeSwapy** [3mora2/WPP_Whatsapp#6]
I am looking for wpp register

**Comment by 3mora2** [comment]
if you mean register like whatsapp apk (through verify code), No, try [yowsup](https://github.com/tgalal/yowsup), [dependents](https://github.com/tgalal/yowsup/network/dependents)

in [WPP_Whatsapp](https://github.com/3mora2/WPP_Whatsapp) scan qrcode from browser
