### ISSUE TITLE
Windows Access denied

### ISSUE THREAD

**Issue by Adhithya-Pinghley** [3mora2/WPP_Whatsapp#8]
I have done pip install wpp_whatsapp and run this code in one system, in which it runs without any problem. But I'm trying to run it on a different system, which throws the below attached error, which apparently says that there is some permission error- I suppose it requires some higher privileges. So I tried to give permission using runas administrator command, but unfortunately I forgot the password. Is there any way I can bypass this issue?? If you need any more information I'm ready to provide  

[Error.txt](https://github.com/3mora2/WPP_Whatsapp/files/12050367/Error.txt)
[whatsapptestfile.txt](https://github.com/3mora2/WPP_Whatsapp/files/12050368/whatsapptestfile.txt)

**Comment by 3mora2** [comment]
issue from [psutil](https://github.com/giampaolo/psutil), please add new issue [here](https://github.com/giampaolo/psutil/issues)

for now to skip it, update `WPP_Whatsapp`
```
git clone https://github.com/3mora2/WPP_Whatsapp.git
cd WPP_Whatsapp
pip install -U .
```
add `check_open_dir=False`
`creator = Create(session=your_session_name, check_open_dir=False)`
